# Generated by Django 5.2.7 on 2026-01-30 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('protein', models.FloatField(default=0)),
                ('energy', models.FloatField(default=0)),
                ('ether_extract', models.FloatField(default=0)),
                ('crude_fiber', models.FloatField(default=0)),
                ('calcium', models.FloatField(default=0)),
                ('phosphorus', models.FloatField(default=0)),
                ('a_phosphorus', models.FloatField(default=0)),
                ('salt', models.FloatField(default=0)),
                ('sodium', models.FloatField(default=0)),
                ('chloride', models.FloatField(default=0)),
                ('lysine', models.FloatField(default=0)),
                ('methionine', models.FloatField(default=0)),
                ('threonine', models.FloatField(default=0)),
                ('arginine', models.FloatField(default=0)),
                ('leucine', models.FloatField(default=0)),
                ('tryptophan', models.FloatField(default=0)),
                ('linoleic', models.FloatField(default=0)),
                ('choline', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('min_inclusion', models.FloatField(default=0)),
                ('max_inclusion', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeedFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=50)),
                ('life_stage', models.CharField(max_length=50)),
                ('optimization_id', models.CharField(blank=True, max_length=50, null=True)),
                ('run_number', models.PositiveIntegerField(default=1)),
                ('total_cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedFormulaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusion_rate', models.FloatField()),
                ('cost', models.FloatField()),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='formulation.feedformula')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulation.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='NutrientRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('animal_type', models.CharField(max_length=50)),
                ('life_stage', models.CharField(max_length=50)),
                ('protein_min', models.FloatField(default=0)),
                ('energy_min', models.FloatField(default=0)),
                ('ether_extract_min', models.FloatField(default=0)),
                ('crude_fiber_max', models.FloatField(default=0)),
                ('calcium_min', models.FloatField(default=0)),
                ('phosphorus_min', models.FloatField(default=0)),
                ('a_phosphorus_min', models.FloatField(default=0)),
                ('salt_max', models.FloatField(default=0)),
                ('sodium_min', models.FloatField(default=0)),
                ('chloride_min', models.FloatField(default=0)),
                ('lysine_min', models.FloatField(default=0)),
                ('methionine_min', models.FloatField(default=0)),
                ('threonine_min', models.FloatField(default=0)),
                ('arginine_min', models.FloatField(default=0)),
                ('leucine_min', models.FloatField(default=0)),
                ('tryptophan_min', models.FloatField(default=0)),
                ('linoleic_min', models.FloatField(default=0)),
                ('choline_min', models.FloatField(default=0)),
            ],
            options={
                'unique_together': {('animal_type', 'life_stage')},
            },
        ),
        migrations.AddField(
            model_name='feedformula',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formulation.nutrientrequirement'),
        ),
    ]
