# Generated by Django 5.2.12 on 2026-04-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formulation", "0002_nutrientrequirement_a_phosphorus_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutrientrequirement",
            name="methionine_cystine_max",
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name="nutrientrequirement",
            name="methionine_cystine_min",
            field=models.FloatField(default=0),
        ),
    ]
