# Generated by Django 5.2.12 on 2026-04-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formulation", "0003_nutrientrequirement_methionine_cystine_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="cystine",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="methionine_cystine",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="a_phosphorus_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="a_phosphorus_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="arginine_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="arginine_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="calcium_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="calcium_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="chloride_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="chloride_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="choline_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="choline_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="crude_fiber_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="crude_fiber_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="energy_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="energy_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="ether_extract_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="ether_extract_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="leucine_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="leucine_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="linoleic_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="linoleic_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="lysine_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="lysine_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="methionine_cystine_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="methionine_cystine_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="methionine_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="methionine_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="phosphorus_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="phosphorus_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="protein_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="protein_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="salt_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="salt_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="sodium_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="sodium_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="threonine_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="threonine_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="tryptophan_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="tryptophan_min",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
